name: Build Godot Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Android SDK
        uses: android-actions/setup-android@v4

      - name: Export Godot Android APK
        uses: NodotProject/godot-export@v7.0.0
        with:
          godot_executable_download_url: https://downloads.tuxfamily.org/godotengine/4.5/Godot_v4.5-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://downloads.tuxfamily.org/godotengine/4.5/Godot_v4.5-stable_export_templates.tpz
          relative_project_path: ./
          presets_to_export: Android
          export_debug: true
          use_preset_export_path: true
          cache: true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: ShimeonBattleRoyale-APK
          path: '**/*.apk'
          if-no-files-found: error
